django12/src/blog/urls.py
from django.urls import path
from .views import *
app_name='blog'

urlpatterns=[
    path('', Index.as_view(), name='index'),
    path('<int:pk>/', Detail.as_view(), name='detail'),
    path('postP/', PostRegister.as_view(), name='postP'),
    path('search/', SearchP.as_view(), name='searchP'),
    
    ]

django12/src/django12/urls.py
from django.contrib import admin
from django.urls import path, include
from bookmark.views import index,booklist, bookdetail
#inlcude():하위 URLConf파일을 추가할 때 사용하는 함수
# urlpatterns : URL과 뷰함수를 등록 및 관리하는 변수
#RUL등록 시 path 함수를 이용해 urlpatterns의 요소를 추가
#path(URL주소( 문자열),  호출할 뷰함수/클래스 이름)
#웹서버 기본주소:127.0.0.1:8000/
urlpatterns = [
    #기본주소+admin 주소로 클라이언트가 요청한 경우, admin 폴더/site.py/urls 함수가 실행
    path('a1/', admin.site.urls),
    path('',index), #127.0.0.1:8000으로 클라이언트가 요청했을 때, index함수가 호출
    path('list/',booklist),
    #127.0.0.1:8000/detail/숫자/로 요청시 bookdetail 호출, 숫자데이터는 bookid 저장이 됨
    path('detail/<int:bookid>/', bookdetail),
    #127.0.0.1:/8000/vote/ 로 시작하는 모든 요청을 vote폴더의 urls.py에서 처리하도록 등록
    path('vote/',include('vote.urls')),
    path('cl/', include('customlogin.urls')),
    #해당 어플리케이션의  app_name 변수에 저장된 문자열 대신 사용할 그룹이름을 namespace 매개변수에 대입시키면 됨
    #127.0.0.1:8000/auth/
    path('auth/', include('social_django.urls', namespace='social')),
    path('blog/', include('blog.urls'))
]
from django.conf import settings #setting.py에 설정된 값을 가져오기 위함
from django.conf.urls.static import static#Media_url과 root을 연동하기 위한 함수

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

django12/src/vote/urls.py
'''
Created on 2018. 12. 16.

@author: user
'''
from django.urls import path
from .views import *

app_name='vote'#하위 URL파일의 그룹이름
#path함수를 이용해 url과 함수를 등록
#기본 주소:127.0.0.1:8000/vote/주소로 요청해야 vote의 index 함수가 호출됨
urlpatterns=[
    path('', index, name='index'),
    path('int:qid/', detail, name='detail'),
    path('vote/',vote,name='vote'),
    path('result/<int:q_id>/', result, name="result"),
    # 127.0.0.1:8000/vote/qr/
    path('qr/', qregister, name='qregister'),
    path('qu/<int:q_id>/', qupdate, name='qupdate'),
    path('qd/<int:q_id>/', qdelete, name="qdelete"),
    path('cd/<int:c_id>/', cdelete, name="cdelete"),
    path('cr/', cregister, name='cregister'),
    path('cu/<int:c_id>/', cupdate, name='cupdate')
    ]

django12/src/vote/models.py
from django.db import models

# 질문
# 질문제목 생성일
class Question(models.Model):
    name = models.CharField('설문조사 제목',max_length=100)
    #DateTimeField:날짜와 시간데이터를 저장하는 공간을 정의할 때 사용하는 클래스
    #DateField:날짜 데이터만 저장하는 공간
    date = models.DateTimeField()
    def __str__(self):
        return self.name
#답변

#어떤 질문에 연결돼있는지 답변내용
class Choice(models.Model):
    name=models.CharField('답변항목',max_length=50)
    #IntegerField:정수값을 저장하는 공간
    votes=models.IntegerField('투표수',default=0)
    #ForeignKey(연결할 모델클래스): ForeignKey 객체를 만든 클래스의 객체들이
    #연겷한 모델클래스의 객체와 연결할 수 있는 설정
    q= models.ForeignKey(Question, on_delete=models.CASCADE)
    def __str__(self):
        return self.q.name+"/"+self.name

class Meta:#모델클래스에 정의된 변수들을 처리할 때 사용하는 클래스
     vervose_name='답변항목'
     ordering=['q']

django12/src/vote/forms.py
'''
Created on 2018. 12. 22.

@author: user
'''
from django.forms.models import ModelForm
from .models import Question, Choice

class QuestionForm(ModelForm):
    class Meta:
        model = Question
        fields = ['name']

class ChoiceForm(ModelForm):
    class Meta:
        model = Choice
        fields = ['q', 'name']

django12/src/vote/views.py
from django.shortcuts import render, get_object_or_404
from .models import Question, Choice

from django.http.response import HttpResponseRedirect
from django.urls import reverse
from vote.forms import ChoiceForm

#HTML문서를 넘겨주는 것이 아닌 리다이렉트 주소를 넘겨줄 때 HttpResponseRedirect 클래스의 객체를 반환하면 됨
#HttpResponseRedirect(사용자에게 넘겨줄 주소(문자열))

#reverse:템플릿에서 url태그와 동일한 기능을 수행. 별칭을 기반으로 한 URL검색
#reverse:(등록된 별칭(문자열), args=(매개변수에 넘겨줄 값,))

#HttpResponseRedirect(reverse())
# index(질문 리스트)
def index(request):
    #Question 객체를 모두 추출
    a=Question.objects.all()
    #HTML문서에 객체 리스트 전달 후 클라이언트에게 HRML파일 전송
    return render(request,'vote/index.html',{'a':a})
#detail(질문 선택 시 답변항목 제공)
def detail(request,qid):
    #get_object_or_404(모델클래스, 조건) : 해당하는 모델클래스에서 조건에 맞는 객체 한 개를 추출
    #조건에 맞는 객체가 한개도 없는 경우, 사용자가 잘못 요청한 것으로 처리해 404 에러를 띄우는 처리를 해줌
    
    b=get_object_or_404(Question, id=qid)#Question.objects.get(id=qid)
    return render(request, 'vote/detail.html',{'q':b})
#vote(웹 틀라이언트 요청에 따라 투표 적용)
def vote(request):
    #POST방식으로 사용자가 요청했는지 확인
    #request.method:사용자의 요청방식이 문자열 형태로 저장된 변수
    if request.method == "POST":
        #request.POST:POST방식으로 요청하면서 넘어온 데이터(사전형)
        #request.POST.get(키값):POST방식으로 넘어온 데이터 중 입력한 키값과 동일한 데이터를 추출
        c_id=request.POST.get('a')
        c= get_object_or_404(Choice, id=c_id)
        c.votes +=1 #투표수 증가
        c.save()#변동사항을 데이터베이스에 반영
        
        #vote어플리케이션의 index뷰로 이동할 수 있도록 URL주소를 넘겨줌
        #c.q:Choice 객체 c에 저장된 q를 접근-> c와 연결된 Question 객체 자체를 의미
        #c.q.id:Choice객체 c와 연결된 Question 객체의 id변수값을 가져옴
        return HttpResponseRedirect(reverse('vote:result',args=(c.q.id,)))
#result(투표결과)
def result(request, q_id):
    
    return render(request, 'vote/result.html',{'q':get_object_or_404(Question, q_id)})

from .forms import QuestionForm, ChoiceForm
from _datetime import datetime #현재 날짜 시간을 불러오는 파이썬 내장 함수

from django.contrib.auth.decorators import login_required
#데코레이터: URL요청에 따라 뷰함수를 호출하는 데, 호출전에 데코레이터가 먼저 실행되서 
#초기화작업, 로그인확인, 접근권한 확인을 수행하는 기능
#함수에 데코레이터 붙이기
#@데코레이터 이름
#def func1()

# 클래스에 데코레이터 붙이기
#class Class(사용할 데코레이터 클래스명):

#login_required: 뷰함수 호출 전 요청을 한 클라이언트가 로그인을 했는지 여부를 파악하고 비로그인 상태일 경우 로그인페이지를 띄워주는 데코레이터 함수

#Question 객체를 사용자가 등록하는 뷰
@login_required
#Choice 객체를 ㅏ용자가 등록하는 뷰
def qregister(request):
    #Get방식 처리
    if request.method=="GET":
    #모델폼클래스 객체 생성
    #모델폼클래스 객체 생성시 매개변수에 값을 전달하지 않는경우, 입력양식에 값이 비어있는 형태로 객체가 생성됨
        form = QuestionForm()
        #HTML 파일 전달
        return render(request, 'vote/qregister.html',{'f':form})
    #POST방식 처리
    elif request.method =="POST":
        #사용자 요청정보를 받아 데이터베이스에 저장
        #request.POST: 사용자가 POST방식으로 요청했을 때 같이 넘어온 데이터 집합(사전형)
        print(request.POST)
        #사용자 입력을 해당 폼객체 생성시 넣음
        form=QuestionForm(request.POST)
        if form.is_valid():# 사용자가 입력한 갓이 유효한 값인지 확인
            #폼객체.cleaned_data:is_valid() 함수로 유효한 값인지 확인 후  True값을 반환했을 때, 
            #사용자의 입력정보를 확인할 수 있는 사전형 변수
            #폼객체.save():모델폼클래스의 객체만 사용가능, 연동된 모델클래스의 객체로 변환 후 데이터베이스에 저장
            #폼객체.save(commit=False):연동된 모델클래스의 객체로 변환만 해줌
            
            #Question 객체는  date 변수에 값이 비어있으면 안되므로 파이썬 코드로 date변수값을 채운 후 DB에 저장해야 함
            q= form.save(commit=False)#q: form에 저장된 값을 바탕으로 생성된 Question 객체
            print('생성된question 객체',q)
            q.date = datetime.now() #파이썬 모듈을 이용해 현재시간을 생성된 Question 객체의 date 변수에 저장
            q.save()#해당 Question 객체를 데이터베이스에 저장
            
            return HttpResponseRedirect(reverse('vote:index'))
# Choice 객체의 데이터를 사용자가 수정하는 뷰
@login_required
def qupdate(request, q_id):
    obj = get_object_or_404(Question, id=q_id)
    if request.method == "GET":
        #데이터베이스에 저장된 Question 객체의 정보를 기반으로 모델폼 객체를 생성
        #HTML로 변환 시 빈칸이 아닌 값이 채워진 형태로 변환됨
        form = QuestionForm(instance = obj)
        return render(request, "vote/qupdate.html",{'f':form})
    elif request.method == "POST":
        #기본 객체에 저장된 변수값을 사용자의 입력데이터로 변경한 모델폼 객체를 생성
        form=QuestionForm(data= request.POST, instance = object)
        if form.is_valid():#수정한 값이 유효한 값인지 확인
            #사용자가 입력한 데이터를 바탕으로 데이터베이스에 수정사항을 반영
            q= form.save()
            print('obj:', obj)
            print('q:', q)
            return HttpResponseRedirect(reverse('vote:index'))


# Choice객체를 사용자가 수정하는 뷰
@login_required
def cupdate(request,c_id):
    c=get_object_or_404(Choice, id=c_id)
    if request.method == "GET":
        form= ChoiceForm(instance = c)
        return render(request, 'vote/cupdate.html',{'f':form})
    elif request.method == "POST":
        form= ChoiceForm(data=request.POST, instance=c)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('vote:detail', args=(c.q.id,)))
        else:
            pass
def cregister(request):
    if request.method == "GET":
        return render(request, 'vote/cregister.html',{'f':ChoiceForm()})
    elif request.method == "POST":
        form=ChoiceForm(request.POST)
        if form.is_valid():
            #더이상 비어있는 변수가 없으므로 데이터베이스 저장과 객체변환을 동시에 실행
            c=form.save()
            print(c)
            return HttpResponseRedirect(reverse('vote:detail', arg=(c.q.id,)))
        else:#사용자의 입력이 유효한 값이 아닌경우
            #사용자가 입력한 데이터를 바탕으로 생성된 form객체와 error변수를 HTML파일에 전달
            return render(request,'vote/cregister.html', {'f':form , 'error':'유효하지 않은 값입니다.'})

#Question 객체 삭제요청 처리 뷰
@login_required
def qdelete(request, q_id):
    #삭제할 객체를 찾기
    q=get_object_or_404(Question, id=q_id)
    #해당객체를 데이터베이스에서 삭제함. 삭제한 객체에 저장된 변수의 값은 사용할 수 있음
    q.delete()
    return HttpResponseRedirect(reverse('vote:index'))
#Choice 객체 삭제 요청 처리 뷰
@login_required
#1)매개변수를 추가(삭제하고자 하는 Choice 객체의 id값)
def cdelete(request, c_id):
    #2)매개변수로 Choice 객체 찾기
    c=get_object_or_404(Choice, id=c_id)
    #3)해당객체 삭제
    c.delete()
    #4)index나 detail의 URL을 전달
    return HttpResponseRedirect(reverse('vote:index'))
    #5)vote폴더에 있는 urls.py 에 뷰함수 등록
     


django12/src/vote/templates/vote/cregister.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>
<h1>답변 등록</h1>
<!-- error변수에 값이 있는 경우 값을 출력 -->
<!-- GET요청으로 HTML파일이 error변수를 못받은경우->none값이 저장됨
POST 요청 중 유효성 검사를 실패한경우 ->str타입의 값이 저장됨 -->
{% if error %}
<p style="color:redzzc">{{ error }}</p>
{% end if %}
<form action="" method="POST">
{% csrf_token%}
<table>
{{f.as_table}}
</table>
<input type="submit" value="답변등록">
</form>
</body>
</html>

django12/src/vote/templates/vote/cupdate.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>
<h1>답변 수정</h1>
<form action="" method="POST">
{% csrf_token%}
{{f.as_p}}
<input type="submit" value="수정">
</form>
</body>
</html>

django12/src/vote/templates/vote/detail.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>
<h1>{{q.name}}</h1>
<p>{{q.date}}</p>
<form action="{%url 'vote:vote'%}" method="POST">
{% csrf_token %}
{# 모델 클래스 A 의 객체, 모델클래스 B_set: 외래키로 연결되있는 다른 모델클래스의 객체를 추출 기법#}
{#q.choice_set:Question객체 q에 연결된 Choice 객체를 대상으로 all(), get(), filter()을 이용해 추출할 수 있음#}
{HTML코드 내에서 파이썬 함수를 쓸 때는 함수이름만 기입
{%for c in q.choice_set.all %}
    <input type="radio" name="a" value="{{c.id}}">
    <label>{{c.name}}</label>
    <a href="{% url 'vote:cupdate' c.id%}">수정</a>
    <a href="{% url 'vote:cdelete' c.id%}">삭제</a>
    <br>
{% endfor%}
<input type="submit" value="투표하기">
</form>
<a href = "{% url 'vote:qupdate' q.id%}">수정</a>
<a href = "{% url 'vote:qdelete' q.id%}">삭제</a>
<br>
<a href="{% url 'vote:index' %}">돌아가기</a>
</body>
</html>

django12/src/vote/templates/vote/index.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>
<h1>투표 어플리케이션</h1>
<p>투표할 질문을 선택하세요</p>
<table>
<tr>
<th> 질문 번호 </th>
<th> 제목 </th>
<th> 생성일 </th>
</tr>
{% for q in a%}
<tr>
<td>{{q.id}}</td>
<td><a href="{% url 'vote:detail' q.id %}">{{q.name}}</a></td>
<td>{{q.date}}</td>
</tr>
{% endfor %}
</table>
<a href="{% url 'vote:qregister' %}">설문조사 등록</a>
<a href = "{% url 'vote:cregister' %}" >답변 등록</a>
</body>
</html>

django12/src/vote/templates/vote/qregister.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>
<h1>설문조사 등록</h1>
<form action="" method="POST">
{% csrf_token %}
<!-- view 에서 넘겨준 변수 f==QuestionForm객체
f.as_p 함수: 각각의 입력양식(<input>)을 <p></p>사이에 넣는 형식으로 HTMl 코드 생성
f.as_table :<tr><td>태그 사이에 <input>을 넣는 형식으로 HTML코드 생성 -->
{{f.as_p }}
<input type="submit" value="질문등록">
</form>
</body>
</html>

django12/src/vote/templates/vote/qupdate.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>
<h1>설문조사 수정</h1>
<form action="" method="POST">
{% csrf_token%}
<table>
{{f.as_table}}
</table>
<input type="submit" value="질문수정">
</form>
</body>
</html>

django12/src/vote/templates/vote/result.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>
<h1>{{q.name}} 투표결과</h1>
<ul>
{% for c in q.choice_set.all)%)
<li>{{c.name}}-{{c.vote}} 표</li>
{% endfor %)
</ul>
<a= href="{% url 'vote:index'%}">메인페이지로 돌아가기</a>
</body>
</html>